[project]
name = "prog-image"
version = "0.1.0"
description = "Image Storage and Retrieval"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aioboto3>=15.5.0",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "pillow>=12.3.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "pytest>=9.1.1",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]

[dependency-groups]
dev = [
    "pytest-asyncio>=1.4.0",
]
