[project]
name = "prog-image"
version = "0.1.0"
description = "Image Storage and Retrieval"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.79",
    "fastapi>=0.141.1",
    "pillow>=12.3.0",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]
